### ISSUE TITLE
Use 'latex' as raw format rather than 'tex'

### ISSUE THREAD

**Issue by joshuahhh** [uwdata/living-papers#72]
Currently, Living Papers assumes raw tex code will be labeled with format 'tex' rather than 'latex'. This deviates from Pandoc's built-in / documented practice. Living Papers needs to explicitly rewrite the format:

https://github.com/uwdata/living-papers/blob/804b7225534a79bb4a3540503e981253f6a1bf6f/packages/compiler/src/plugins/include/index.js#L56

Also, the Pandoc documents [refer to using {=latex} for a raw latex block](https://pandoc.org/MANUAL.html#extension-raw_attribute:~:text={=latex}).

Not sure why we should use 'tex' rather than 'latex', since 'latex' is the name we use for the output format elsewhere (like in `latex:only`, etc.). At the very least, I'd like this condition to include 'latex':

https://github.com/uwdata/living-papers/blob/804b7225534a79bb4a3540503e981253f6a1bf6f/packages/compiler/src/output/latex/tex-format.js#L385-L388

Happy to make the change if desired.

**Comment by jheer** [comment]
I default to `tex` because that is what the Pandoc markdown parser produces by default (e.g., [see this example](https://pandoc.org/try/?params=%7B%22text%22%3A%22%5C%5Cvspace%7B12pt%7D%22%2C%22to%22%3A%22native%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)).

Ideally everything could use `latex` to match the Living Papers output type name. One possibility would be to augment our Pandoc AST parser to simply map raw `tex` to raw `latex`. Alternatively, we could have both `tex` and `latex` map to the same semantics, though this might involve some new patches (possibly including to the recently added `excludesNamespace` AST utility). The first option feels "nicer" to me.
